version: "3.7"
services:
  api:
    container_name: todo-list-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE=postgres
      - USER=postgres
      - PASSWORD=postgres
      - HOST=postgres
      - PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: todo-postgres
